# Generated by Django 4.2.20 on 2025-03-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
