# Generated by Django 4.2.20 on 2025-03-15 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_content_message_message_remove_message_topic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
